### ISSUE TITLE
How to integrate with Django?

### ISSUE THREAD

**Issue by elcolie** [mayoturis/logstats#2]
How to integrate with Django Logger?

**Comment by mayoturis** [comment]
Currently, there isn't any Python library (or any other out of the box integration with Django). But log messages are sent as HTTP POST requests in simple format, so building own library on top of HTTP client shouldn't take more than one hour. Required format of messages is described in [documentation](http://logstats.org/sending-logs-other)

**Comment by elcolie** [comment]
Thank you very much. If I have question I will ask you again
